src/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: 'tops#index'

  resources :jade_features, only: [:index]

  resources :questions, only: [:index]
  get 'answer/:answer', to: 'questions#answer', as: :answer
  get '/answer', to: 'questions#answer'
  get 'result', to: 'questions#result'
  get 'questions_path', to: 'questions#reset_score'
  get 'start', to: 'questions#start'
  post '/answer', to: 'questions#answer', as: :post_answer
  get 'easy_gam', to: 'questions#easy_gam'
  get 'normal_gam', to: 'questions#normal_gam'
  get 'hard_gam', to: 'questions#hard_gam'
end

src/app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

src/app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

src/app/controllers/jade_features_controller.rb
# frozen_string_literal: true

class JadeFeaturesController < ApplicationController
  def index; end
end

src/app/controllers/questions_controller.rb
# frozen_string_literal: true

class QuestionsController < ApplicationController
  before_action :set_buttons, only: %i[easy_gam normal_gam hard_gam]

  def index
    session[:total_count] = 0
    session[:started] = false
  end

  def set_buttons
    @hisui_buttons = (1..29).map { |i| ["hisui/hisui#{i}.jpg"] }
    @stones_buttons = (1..43).map { |i| ["stones/stones#{i}.jpg"] }
  end

  def easy_gam
    @easy_shuffled_buttons = [@hisui_buttons.sample, @stones_buttons.sample].shuffle
  end

  def normal_gam
    @normal_shuffled_buttons = [@hisui_buttons.sample] + @stones_buttons.sample(4)
    @normal_shuffled_buttons.shuffle!
  end

  def hard_gam
    @hard_shuffled_buttons = [@hisui_buttons.sample] + @stones_buttons.sample(9)
    @hard_shuffled_buttons.shuffle!
  end

  def answer
    session[:correct_count] ||= 0
    session[:total_count] ||= 0

    if params[:answer] == 'hisui'
      flash[:notice] = '正解！'
      session[:correct_count] += 1
    else
      flash[:alert] = '不正解...'
    end

    session[:total_count] += 1

    if session[:total_count] >= 10
      redirect_to result_path and return
    else
      redirect_to request.referer || normal_gam_path
    end
  end

  def start
    session[:correct_count] = 0
    session[:total_count] = 0
    session[:started] = true
    redirect_back(fallback_location: normal_gam_path)
  end

  def result
    session[:total_count] = 0
    session[:started] = false
  end
end

src/app/controllers/tops_controller.rb
# frozen_string_literal: true

class TopsController < ApplicationController
  def index; end
end

src/app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

src/app/helpers/jade_features_helper.rb
# frozen_string_literal: true

module JadeFeaturesHelper
end

src/app/helpers/questions_helper.rb
# frozen_string_literal: true

module QuestionsHelper
end

src/app/helpers/tops_helper.rb
# frozen_string_literal: true

module TopsHelper
end

src/app/views/Buttons/_change -Mode-Button.html.erb
<%= link_to "モードを変更する", questions_path, class: "w-full sm:w-auto mt-10 rounded-lg bg-green-500 border-none text-white px-8 py-4 text-center no-underline inline-block text-lg" %>

src/app/views/Buttons/_game-Screen-Button.html.erb
<%= link_to "ゲーム画面へ", questions_path, class: "w-full sm:w-auto mt-10 rounded-lg bg-green-500 border-none text-white px-8 py-4 text-center no-underline inline-block text-lg" %>

src/app/views/Buttons/_game-Start-Button.html.erb
<%= link_to 'ゲームスタート', start_path(mode: 'normal'), class: 'btn btn-primary w-full sm:w-auto mt-10 rounded-lg bg-blue-500 border-none text-white px-8 py-4 text-center no-underline inline-block text-lg ' %>

src/app/views/Buttons/_hisui-About-Button.html.erb
<%= link_to 'ヒスイの特徴', jade_features_path(mode: 'normal'), class: "w-full sm:w-auto mt-10 rounded-lg bg-green-500 border-none text-white px-8 py-4 text-center no-underline inline-block text-lg" %>

src/app/views/Buttons/_reset-Button.html.erb
    <%= link_to '最初からやり直す', start_path(mode: 'normal'), class: 'btn btn-primary w-full sm:w-auto mt-10 rounded-lg bg-blue-500 border-none text-white px-8 py-4 text-center no-underline inline-block text-lg ' %>

src/app/views/Buttons/_return-Button.html.erb
<%= link_to 'もう一度やる', request.referer || normal_gam_path, class: "w-full sm:w-auto mt-10 rounded-lg bg-blue-500 border-none text-white px-8 py-4 text-center no-underline inline-block text-lg"  %>

src/app/views/Buttons/_top-Page-Button.html.erb
  <%= link_to "TOPページに戻る", root_path, class: "w-full sm:w-auto mt-10 rounded-lg bg-green-500 border-none text-white px-8 py-4 text-center no-underline inline-block text-lg " %>

src/app/views/jade_features/index.html.erb
<div class="text-gray-600 w-full min-h-screen flex flex-col items-center justify-center">
  <div class="w-full mt-20 sm:mt-4 text-center ">
    <div class="w-full mt-5 border-t"></div>
    <h1 class="text-2xl sm:text-2xl mt-5">ヒスイの特徴</h1>
    <%= link_to "見分け方のコツ", "https://www.happousyumi.com/entry/hisui-mikiwame", class: "text-blue-600 underline" %>
  </div>
  <div class="w-full mt-5 border-t"></div>
  <h1 class="text-2xl mt-2 text-center">ヒスイって何だろう</h1>
  <div class="mt-2 text-center">
    <%= link_to "フォッサマグナミュージアム", "https://fmm.geo-itoigawa.com/event-learning/about_hisui", class: "text-blue-600 underline" %>
  </div>
  <div class="w-full mt-5 border-t"></div>
  <div class="text-center">
    <h1 class="text-2xl sm:text-2xl mt-2">ヒスイの鑑定をしてくれるところ</h1>
    <ul class="mt-2">
      <li class="mt-2"><%= link_to "フォッサマグナミュージアム", "https://fmm.geo-itoigawa.com/info/appraisal/", class: "text-blue-600 underline" %></li>
      <li class="mt-2"><%= link_to "ヒスイテラス", "https://www.asahi-tabi.com/asahimachi/1609/", class: "text-blue-600 underline" %></li>
    </ul>
  </div>
  <div class="w-full mt-5 border-t"></div>
  <div class="text-center sm:text-left">
    <div class="mt-5 mb-20 grid grid-cols-1 sm:grid-cols-2 gap-4 ">
      <%= render "Buttons/game-Screen-Button" %>
      <%= render "Buttons/top-Page-Button" %>
    </div>
  </div>
</div>

src/app/views/layouts/_Button to return to the top page.html.erb
  <%= link_to "TOPページに戻る", root_path, class: "w-full sm:w-auto mt-10 rounded-lg bg-green-500 border-none text-white px-8 py-4 text-center no-underline inline-block text-lg " %>

src/app/views/layouts/_footer.html.erb
<footer class="text-gray-600 fixed bottom-0 inset-x-0 h-17 border-t bg-white">
  <p class="max-w-7xl mx-auto text-center py-2 ">© Hisui maste guild All rights reserved.</p>
</footer>

src/app/views/layouts/_game start button.html.erb
<%= link_to "ゲーム画面へ", questions_path, class: "w-full sm:w-auto mt-10 rounded-lg bg-green-500 border-none text-white px-8 py-4 text-center no-underline inline-block text-lg" %>

src/app/views/layouts/_header.html.erb
<header class=" text-gray-600 fixed top-0 w-full bg-white flex items-center justify-between px-4 py-3 border-b-2">
  <%= link_to "ヒスイマスター", root_path, class: "text-6xl text-lg font-semibold" %>
</header>

src/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="bg-green-300 w-full >
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-2HKJ832ZFM"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-2HKJ832ZFM');
    </script>
  </head>
  <body>
    <main>
      <%= render "layouts/header" %>
      <%= yield %>
    </main>
    <%= render "layouts/footer" %>
  </body>
</html>

src/app/views/questions/_modes.html.erb
<h1 class="text-5xl text-white text-center mt-20"><%= @mode_name %></h1>
<% if session[:started] %>
  <% if flash[:notice] %>
    <div class="flex items-center justify-center h-screen">
      <p class="text-8xl text-red-500">〇</p>
    </div>
    <script>
      setTimeout(function() {
        window.location.reload();
      }, 250);
    </script>
  <% elsif flash[:alert] %>
    <div class="flex items-center justify-center h-screen">
      <p class="text-8xl text-blue-500">×</p>
    </div>
    <script>
      setTimeout(function() {
        window.location.reload();
      }, 250);
    </script>
  <% else %>
    <h1 class="text-5xl text-white text-center mt-10">問題 <%= session[:total_count]&.next %></h1>
    <div class="flex justify-center mt-10">
      <div class="flex mt-10">
        <div class="grid grid-cols-2 gap-4">
          <% buttons.each do |button| %>
            <div class="flex items-center justify-center">
              <%= button_to answer_path(answer: button[0].split('/')[0]), method: :get, class: 'image-button' do %>
                <%= image_tag button[0], alt: button[1], class: 'rounded-full w-24 h-24 sm:w-32 sm:h-32 mr-5' %>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="mt-5 mb-40 grid grid-cols-1 sm:grid-cols-2 gap-4 ">
      <%= render "Buttons/reset-Button" %>
      <%= render "Buttons/change -Mode-Button" %>
    </div>
  <% end %>
<% else %>
  <div class="mt-5 mb-40 grid grid-cols-1 sm:grid-cols-2 gap-4 ">
    <%= render "Buttons/game-Start-Button" %>
    <%= render "Buttons/game-Screen-Button" %>
  </div>
<% end %>

src/app/views/questions/easy_gam.html.erb
<% buttons = @easy_shuffled_buttons.first(10) %>
<% @mode_name = "イージーモード" %>
<%= render partial: "questions/modes", locals: { mode_name: @mode_name, buttons: buttons } %>


src/app/views/questions/hard_gam.html.erb
<% buttons = @hard_shuffled_buttons.first(10) %>
<% @mode_name = "ハードモード" %>
<%= render partial: "questions/modes", locals: { mode_name: @mode_name, buttons: buttons } %>

src/app/views/questions/index.html.erb
<div class=" w-full flex flex-col items-center justify-center">
  <h1 class="mt-20 text-2xl sm:text-4xl md:text-6xl text-white text-center font-bold w-full" style="text-shadow: 0 0 10px rgba(0,0,0,0.5)">
    翡翠ギルド検定試験
  </h1>
  <div class="mt-10 bg-white p-8 rounded-lg shadow-lg text-gray-600">
    <p class="text-lg">モードを選択してください</p>
    <p class="text-lg">ヒスイの画像をクリックしください</p>
    <p class="text-lg">全部で10問です</p>
    <p class="text-lg">イージーモードは2択、ノーマルモードは5択、ハードモードは10択</p>
    <p class="text-lg">高ランク冒険者を目指して頑張ろう！</p>
    <h1 class="text-2xl font-bold mt-4">ヒスイギルドランク</h1>
    <p class="text-lg">
      ヒスイマスター : 9点～10点<br>
      上級ヒスイ冒険者 : 7点～8点<br>
      中級ヒスイ冒険者 : 5点～6点<br>
      初級ヒスイ冒険者 : 3点～4点<br>
      ヒスイ初心者 : 0点～2点
    </p>
  </div>
  <div class="mb-15 ">
    <%= link_to 'イージーモード', easy_gam_path(mode: 'easy'), class: 'btn btn-primary w-full sm:w-auto mt-10 rounded-lg bg-yellow-500 border-none text-white px-8 py-4 text-center no-underline inline-block text-lg' %>
    <%= link_to 'ノーマルモード', normal_gam_path(mode: 'normal'), class: 'btn btn-primary w-full sm:w-auto mt-10 rounded-lg bg-blue-500 border-none text-white px-8 py-4 text-center no-underline inline-block text-lg' %>
    <%= link_to 'ハードモード', hard_gam_path(mode: 'hard'), class: 'btn btn-primary w-full sm:w-auto mt-10 rounded-lg bg-red-500 border-none text-white px-8 py-4 text-center no-underline inline-block text-lg' %>
    <div class=" mb-20 grid grid-cols-1 sm:grid-cols-2 gap-4 ">
      <%= render "Buttons/hisui-About-Button" %>
      <%= render "Buttons/top-Page-Button" %>
    </div>
  </div>
</div>

src/app/views/questions/normal_gam.html.erb
<% buttons = @normal_shuffled_buttons.first(5) %>
<% @mode_name = "ノーマルモード" %>
<%= render partial: "questions/modes", locals: { mode_name: @mode_name, buttons: buttons } %>

src/app/views/questions/result.html.erb
<div class="flex justify-center h-screen items-center text-gray-600">
  <div class="bg-white p-8 rounded-lg shadow-lg w-full text-center inline-block">
    <h1 class="text-4xl font-bold mb-4 mt-10 ">あなたの点数は <%= session[:correct_count] %>/10点です！</h1>
    <% rank = case session[:correct_count] 
      when 9..10 then 'ヒスイマスター' 
      when 7..8 then '上級ヒスイ冒険者' 
      when 5..6 then '中級ヒスイ冒険者' 
      when 3..4 then '初級ヒスイ冒険者' 
      else 'ヒスイ初心者' 
    end %>
    <p class="text-2xl mb-6">あなたのランクは </p>
    <p class="text-3xl mb-6"><strong><%= rank %></strong>です。</p>
    <%= render "Buttons/return-Button" %>
    <%= render "Buttons/change -Mode-Button" %>
    <%= render "Buttons/top-Page-Button" %>
  </div>
</div>

src/app/views/tops/index.html.erb
<div class=" w-full h-screen flex flex-col items-center justify-center">
  <h1 class="mt-10 text-6xl text-white text-center font-bold w-full" style="text-shadow: 0 0 10px rgba(0,0,0,0.5)">
    ゲームを通じてヒスイを見分けられるようになろう！
  </h1>
  <div class="mb-20 grid grid-cols-1 gap-4">
    <%= render "Buttons/game-Screen-Button" %>
    <%= render "Buttons/hisui-About-Button" %>
  </div>
</div>